const practiceFormElements = {
    practiceFormBtn: '#item-0 > a[href="/automation-practice-form"]',
    practiceForm: 'div.practice-form-wrapper > h1',
    firstNameInput: '#firstName',
    lastNameInput: '#lastName',
    emailInput: '#userEmail',
    genderMaleRadioBtn: '#gender-radio-1',
    genderFemaleRadioBtn: '#gender-radio-2',
    genderOtherRadioBtn: '#gender-radio-3',
    mobileInput: '#userNumber',
    dateOfBirthInput: '#dateOfBirthInput',
    subjectsInput: '#subjectsInput',
    hobbiesCheckboxSports: '#hobbies-checkbox-1',
    hobbiesCheckboxReading: '#hobbies-checkbox-2',
    hobbiesCheckboxMusic: '#hobbies-checkbox-3',
    uploadPictureBtn: '#uploadPicture',
    currentAddressInput: '#currentAddress',
    stateSelect: '#react-select-3-input',
    citySelect: '#react-select-4-input',
    submitBtn: '#submit',
    modalThanksSubmitTitle: '#example-modal-sizes-title-lg',
    modalThanksCloseBtn: '#closeLargeModal',
}

export default practiceFormElements;